functionsDirectory = "/Users/suman.nanjappa/WebstromProjects/Undash-cop/udc-webstack2.0/netlify/functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "/Users/suman.nanjappa/WebstromProjects/Undash-cop/udc-webstack2.0/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/suman.nanjappa/WebstromProjects/Undash-cop/udc-webstack2.0/netlify/functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
external_node_modules = ["formidable", "@aws-sdk/client-s3", "@aws-sdk/s3-request-presigner", "@sendgrid/mail", "zod"]
node_bundler = "esbuild"

[[headers]]
for = "/api/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[[redirects]]
from = "/old-page"
to = "/new-page"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "http://undash-cop.com/*"
to = "https://undash-cop.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://www.undash-cop.com/*"
to = "https://undash-cop.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*/"
to = "/:splat"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/404"
to = "/404.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/500"
to = "/500.html"
status = 500.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/applications"
to = "/.netlify/functions/applications"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/health"
to = "/.netlify/functions/applications"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]